FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml README.md ./
COPY frontend ./frontend

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir streamlit requests pydantic-settings

CMD ["streamlit", "run", "frontend/Home.py", "--server.address=0.0.0.0", "--server.port=8501"]
